### ISSUE TITLE
ai art collection by hacktoberfest community

### ISSUE THREAD

**Issue by vefoto-gates** [vefoto-gates/Ai-art#1]
For any queries regarding your pull requests ask here
Please follow the guidelines in the CONTRIBUTING.md

**Comment by gauravmandall** [comment]
I maked a pull request as per your guidelines please accept my pull request

**Comment by vefoto-gates** [comment]
@gauravmandall you're the first contributor of this project #2

**Comment by vefoto-gates** [comment]
Now the Contribution is over
Thanks for Contributing in this Repository
